export const CorrectHeaders = [
  'Full Name',
  'Phone',
  'Email',
  'Age',
  'Experience',
  'Yearly Income',
  'Has children',
  'License states',
  'Expiration date',
  'License number',
];

export const STATES = {
  ID: 'Idaho',
  IA: 'Iowa',
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  WY: 'Wyoming',
  WA: 'Washington',
  VT: 'Vermont',
  VA: 'Virginia',
  WI: 'Wisconsin',
  HI: 'Hawai`i',
  DE: 'Delaware',
  GA: 'Georgia',
  WV: 'West Virginia',
  IL: 'Illinois',
  IN: 'Indiana',
  CA: 'California',
  KS: 'Kansas',
  KY: 'Kentucky',
  CO: 'Colorado',
  CT: 'Connecticut',
  LA: 'Louisiana',
  MA: 'Massachusetts',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MI: 'Michigan',
  MT: 'Montana',
  ME: 'Maine',
  MD: 'Maryland',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NY: 'New York',
  NM: 'New Mexico',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  ND: 'North Dakota',
  NC: 'North Carolina',
  TN: 'Tennessee',
  TX: 'Texas',
  FL: 'Florida',
  SD: 'South Dakota',
  SC: 'South Carolina',
  UT: 'Utah',
};
